name: chainercv
channels:
- !!python/unicode
  'menpo'
- !!python/unicode
  'mpi4py'
- !!python/unicode
  'defaults'
dependencies:
  - Cython
  - opencv
  - matplotlib
  - numpy
  - Pillow
  - mpi4py
  - scipy
